[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agenticflow"
version = "0.1.0"
description = "LangGraph-based multi-agent workflow orchestration"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "langgraph>=0.2.0",
    "langchain>=0.2.0",
    "langchain-core>=0.2.0",
    "langchain-community>=0.2.0",
    "langchain-experimental>=0.3.0",
    "langchain-groq>=0.1.0",
    "langchain-ollama>=0.2.0",
    "chromadb>=0.5.3",
    "lxml>=5.2.1",
    "python-dotenv>=1.0.1",
    "pydantic>=2.0.0",
    "pyyaml>=6.0",
    "asyncio-mqtt>=0.13.0",
    "aiofiles>=23.0.0",
    "structlog>=23.0.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
select = ["E", "F", "I", "N", "W"]
ignore = []
line-length = 88
target-version = "py310"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
